Add tun mode with sing-tun
v2rayA/v2rayA pull request #1195
Opened 2023-11-24 22:47 UTC by wnxd

需要go编译tags`with_gvisor`
macOS下brew测试需要新增环境变量`V2RAYA_CONFIG: "#{opt_pkgshare}"`

2023-11-24 22:51 UTC, wnxd commented
目前`v2rayA/v2rayA`主分支最新代码我编译会报错 = = 需要把yarn的`compression-webpack-plugin`插件删除才能正常编译

2023-11-25 00:22 UTC, MarksonHon commented
@wnxd 先看下CI能不能过吧，前几天是合并了一个相关的提交，另外，通过sudo启动brew服务，Path变量是包含了brew的路径吧，我现在没黑果了测不了

2023-11-25 00:44 UTC, MarksonHon commented
![图片](https://github.com/v2rayA/v2rayA/assets/50002150/e4576f88-10d5-4c14-9da9-518666df3138)

@mzz2017 CC

CI 看起来不够用，我还是重写一下上Matrix吧，否则不好判断多平台的编译问题，

2023-11-25 01:56 UTC, wnxd commented
@MarksonHon root用户没有`HOME`这个环境变量, v2rayA在readConfig里面有使用`$HOME`导致抛出异常.

2023-11-25 03:19 UTC, MarksonHon commented
@wnxd

2023-11-25 03:33 UTC, wnxd commented
@MarksonHon
我发现了...应该叫`darwin`后缀

2023-11-25 03:37 UTC, MarksonHon commented
@wnxd 目前是不是还没写 linux 的 tun 支持

2023-11-25 03:39 UTC, MarksonHon commented
@wnxd 坏事 Windows的CI我写坏了 先无视

2023-11-25 03:53 UTC, mzz2017 commented
怎么把gzip加回来了，之前有个pr删掉了

2023-11-25 03:53 UTC, MarksonHon commented
先同步下上游，我把 windows 的 ci 修了下

2023-11-25 03:53 UTC, mzz2017 requested changes

2023-11-25 03:53 UTC, mzz2017 commented on build.sh
> +find "$CurrentDir"/service/server/router/web \! -name \*.png -a \! -name \*.gz -a \! -name index.html -a ! -type d -exec gzip -9 {} +
这应该是另一个pr的修改，怎么revert了

2023-11-25 03:59 UTC, wnxd commented on build.sh
> +find "$CurrentDir"/service/server/router/web \! -name \*.png -a \! -name \*.gz -a \! -name index.html -a ! -type d -exec gzip -9 {} +
这个修改的哪.

2023-11-25 04:16 UTC, MarksonHon commented on build.sh
> +find "$CurrentDir"/service/server/router/web \! -name \*.png -a \! -name \*.gz -a \! -name index.html -a ! -type d -exec gzip -9 {} +
> 这应该是另一个pr的修改，怎么revert了

我看了他的分支，通过脚本来压缩已经是删掉了的

2023-11-25 05:52 UTC, MarksonHon commented
![图片](https://github.com/v2rayA/v2rayA/assets/50002150/f63e16dc-9b2d-42f0-aab5-cc995af27167)
有一个问题是，在手动停止服务的情况下，tun接口没有退出

2023-11-25 15:33 UTC, wnxd commented
@MarksonHon 
我look了一遍`sing-tun`关于`GVisor`的实现，发现`GVisor.Close`只调用的`Stack.Close()`异步释放，目前解决方案在不改动`sing-tun`代码的前提上，通过反射去获取`GVisor`的`stack`成员，然后`Close`之后调用`GVisor->stack->Wait()`来等待释放完毕

2023-11-26 01:03 UTC, MarksonHon commented
![图片](https://github.com/v2rayA/v2rayA/assets/50002150/5e13cdd2-1744-4c1d-84b7-f42672754e75)
现在在Linux上好像停不下来了

2023-11-26 01:49 UTC, wnxd commented
@MarksonHon 
我用虚拟机调试一下 = =

2023-11-26 02:37 UTC, wnxd commented
@MarksonHon 
似乎是
github.com/sagernet/gvisor/pkg/tcpip/stack: 1759
`	for id, n := range s.nics {`
`		s.removeNICLocked(id)`
`		n.NetworkLinkEndpoint.Wait()`
`	}`
这段卡住了, 好像在linux无法正常释放

2023-11-26 02:47 UTC, MarksonHon commented
@wnxd 要不，先不提供gvisor的Tun吧，system tun 能用就行

2023-11-26 02:53 UTC, MarksonHon commented
![图片](https://github.com/v2rayA/v2rayA/assets/50002150/6f8a6cfc-b4e4-46df-9fc7-3c2bcd6c7c6a)
又发现个问题，现在没法修改或分享节点了
@mzz2017 CC

2023-11-26 02:59 UTC, wnxd commented
@MarksonHon
我找到问题所在了. sing-tun 会先创建 Tun 对象, 然后提供给 Stack 对象调用 在 linux 有个通讯的loop基于tunFd读取是否报错来判断跳出的, 而tunFd的释放会在 Tun 对象Close时候关闭, 然后我代码里的释放逻辑是从后往前, 先释放 Stack 再释放 Tun, 所以在 Stack 加上 Wait 就会卡死, 我改下这块的释放逻辑.

2023-11-26 03:12 UTC, wnxd commented
@MarksonHon 我修复了, 你看下 = =

2023-11-26 03:22 UTC, mzz2017 commented
> ![图片](https://github.com/v2rayA/v2rayA/assets/50002150/6f8a6cfc-b4e4-46df-9fc7-3c2bcd6c7c6a)
> 
> 又发现个问题，现在没法修改或分享节点了
> 
> @mzz2017 CC

是这个pr导致的吗

2023-11-26 03:31 UTC, MarksonHon commented
@mzz2017 看起来不是，main分支的最新代码就有这个问题

2023-11-26 03:39 UTC, mzz2017 commented
@wnxd 不应该吧，r主席应该不会犯这种错误，关掉tun看看呢

2023-11-26 03:41 UTC, MarksonHon commented
@wnxd 似乎 tun 接口本身需要一个 ipv6 地址，比如 fd::1 这样的

2023-11-26 03:43 UTC, wnxd commented
开启IPv6访问. 用 chrome 和 curl 测试 直接无法访问. 日志查看是转发给xray了, 然后路由判断走的 direct

2023-11-26 03:44 UTC, wnxd commented
@mzz2017 @MarksonHon  你们可以把`f13629e01f32cf4f0b2c3ec947b402cc5ef8f621`这个提交恢复下测下

2023-11-26 03:44 UTC, mzz2017 commented
@wnxd 不开代理的时候ipv6是可以的是吧

2023-11-26 03:49 UTC, wnxd commented
@mzz2017 可以不开tun只开放个代理端口用 `curl -x "socks5://127.0.0.1:1089" https://www.baidu.com -6` 测试.

2023-11-26 03:50 UTC, MarksonHon commented
> ![图片](https://private-user-images.githubusercontent.com/50002150/285626179-6f8a6cfc-b4e4-46df-9fc7-3c2bcd6c7c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NzA4NjAsIm5iZiI6MTcwMDk3MDU2MCwicGF0aCI6Ii81MDAwMjE1MC8yODU2MjYxNzktNmY4YTZjZmMtYjRlNC00NmRmLTlmYzctM2MyYmNkNmM3YzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDAzNDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiN2Q5ZjVjNWRlNDI3ZDU3ZGZhMmM0OWU4NjdkOWQwZTY4NzJmZjZiMGVmN2M2ZWU1ODk5NDJhNTdkODQ5YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h4nnwdEywqkvdZ8GtRMR5veVfOSsfo1PAyNF2QmUlMA) 又发现个问题，现在没法修改或分享节点了 @mzz2017 CC

找到有问题的 commit 了，与本次 PR 无关：
https://github.com/v2rayA/v2rayA/tree/b664fba9d61848cf520ca5f44d4f28f8571dc9d6

2023-11-26 03:51 UTC, mzz2017 commented
@wnxd 那没有代理端口直接 curl 呢

2023-11-26 03:52 UTC, mzz2017 commented
@wnxd 另外使用 ip.sb 试试，baidu 的 v6 支持可能不同区域不一样

2023-11-26 03:53 UTC, wnxd commented
@mzz2017 我好像知道了. 是设置 sendThrough 的原因. 但是现在有个问题是, 如果不设置 sendThrough 的话 xray的流量会回流一遍 tun 然后再直连, 这个问题不好解决, 主要是 xray 与 v2ray 都不支持设置指定网卡出口

2023-11-26 03:55 UTC, mzz2017 commented
> @mzz2017 我好像知道了. 是设置 sendThrough 的原因. 但是现在有个问题是, 如果不设置 sendThrough 的话 xray的流量会回流一遍 tun 然后再直连, 这个问题不好解决, 主要是 xray 与 v2ray 都不支持设置指定网卡出口

开两个 direct，一个directv4一个directv6，根据ipversion分流？

2023-11-26 04:15 UTC, MarksonHon commented
@wnxd 现在能正常关掉了，就是反应慢点，~~还是建议暂时先屏蔽 gvisor tun~~

2024-02-15 06:57 UTC, darcyg commented
@wnxd 我用了你的修改版，现在发现一些问题。
在trojan协议下 旁路由似乎功能正常（dns没有被污染）
但是在ss和vless/vmess模式下，旁路由/tun模式，必须强制设置客户端dns的地址比如1.1.1.1
才能正常使用。
我猜测是tun模式下默认53端口的流量是直接转发出去了，没有截获送到v2raya中的dns模块处理
因为我尝试v2raya的dns中进行配置，但无效。

我对trojan/ss/vless/vmess每个协议我都测试了2-3个机场服务。似乎都是这个问题。

最后，做测试的时候，选了自定义DNS解析的时候，不过一旦填了国际访问的dns处理(我把opendns的那行移到国外访问)
还会导致几分钟内，内存占用从1G猛增到4G，最后系统重启（我用的是arm小主机，在docker环境下，只有4GB内存）。
不确定这个bug是什么造成的。

2024-04-14 14:41 UTC, merged