feat: search for assets in XDG directories
v2rayA/v2rayA pull request #393
Opened 2022-01-27 07:15 UTC by NickCao

Search for (or store) v2ray assets in XDG data directories, instead of using hardcoded pathes.
Also allows different assets to be from different pathes.
Mostly in line with v2ray search pathes, [common/platform/other.go](https://github.com/v2fly/v2ray-core/blob/1df432218eaa71b8c3ec3de0af9308399a90fd56/common/platform/others.go#L32-L37), with a few incompatible ones:
- [ ] `/opt/share/v2ray` only searched by by v2ray
- [ ] `~/.local/share/v2ray (or $XDG_DATA_HOME/v2ray)` only used by v2raya
- [ ] `v2ray directory under $XDG_DATA_DIRS` only searched by v2raya

2022-01-27 07:20 UTC, mzz2017 commented
Maybe Windows should also be considerred.

2022-01-27 11:55 UTC, cubercsl requested changes

2022-01-27 11:55 UTC, cubercsl commented on service/core/v2ray/asset/asset.go
> +            return searchPath, nil
```suggestion
			if _, err = os.Stat(searchPath); err != nil && errors.Is(err, fs.ErrNotExist) {
				continue
			}
			return searchPath, nil
```

2022-01-27 12:34 UTC, mzz2017 reviewed
Thanks for your high code quality work.

However, on windows, I get an error `symlink C:\Users\mzz\AppData\Local\v2ray\geoip.dat C:\Users\mzz\AppData\Local\v2raya\geoip.dat: A required privilege is not held by the client.`

Could you please fix it?

2022-01-27 12:34 UTC, mzz2017 commented on service/core/v2ray/asset/asset.go
> +	if location != "" {
Could we merge the three `if` branches below?

2022-01-27 12:34 UTC, mzz2017 commented on service/core/v2ray/asset/asset.go
> +func IsV2rayAssetExists(filename string) bool {
Sorry for my grammatical errors. Please help me rename it as DoesV2rayAssetExist, and the same below.

2022-01-28 01:30 UTC, NickCao commented
> Thanks for your high code quality work.
> 
> However, on windows, I get an error `symlink C:\Users\mzz\AppData\Local\v2ray\geoip.dat C:\Users\mzz\AppData\Local\v2raya\geoip.dat: A required privilege is not held by the client.`
> 
> Could you please fix it?

Windows requires admin privilege to create symlinks (unless you are using a new enough windows version with developer mode on, which is likely not the case), maybe we should just keep the old behavior of storing everything into config folder on windows, unless V2RAY_LOCATION_ASSET is explicitly set)

2022-01-28 13:05 UTC, mzz2017 requested changes

2022-01-28 13:05 UTC, mzz2017 commented on service/core/v2ray/asset/asset.go
> +		return GetV2rayConfigDirPath()
This is the value of --v2ray-confdir. Do you mean `conf.GetEnvironmentConfig().Config` ? The same below.

2022-01-29 02:33 UTC, mzz2017 approved these changes

2022-01-29 07:19 UTC, cubercsl approved these changes

2022-01-30 04:42 UTC, merged

2022-01-30 04:43 UTC, mzz2017 commented
Thanks for your work. Happy Spring Festival.