optimize: enable allowInsecure for vless
v2rayA/v2rayA pull request #414
Opened 2022-02-14 16:55 UTC by Gaojianli

close https://github.com/v2rayA/v2rayA/issues/410

2022-02-15 14:01 UTC, mzz2017 requested changes
AllowInsecure should be added at line 328.

2022-02-15 17:27 UTC, Gaojianli commented
@Gaojianli 修复了

2022-02-16 11:39 UTC, mzz2017 approved these changes

2022-02-17 11:23 UTC, merged

2022-02-17 11:23 UTC, mzz2017 commented
Nice work. Thanks!